[project]
name = "weather-scrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "pandas>=2.3.0",
    "requests>=2.32.4",
]

[tool.uv.scripts]
# Define a script specifically for this weather-scrapper package
start = "python main.py" 
